global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "my-microservices"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
          - "antiplagiarism:8080"
          - "audit-service:8082"
          - "notification-service:8081"
          - "statistics-service:8084"
          - "plagiarism-analysis-service:8085"