global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "my-microservices"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets:
            - "host.docker.internal:8080"   # antiplagiarism
            - "host.docker.internal:8081"   # notification-service
            - "host.docker.internal:8082"   # audit-service
            - "host.docker.internal:8084"   # statistics-service
            - "host.docker.internal:8085"   # plagiarism-analysis-service